export const CONTRACT_REPOSITORY = Symbol('CONTRACT_REPOSITORY');
export const CREATE_CONTRACT_SERVICE = Symbol('CREATE_CONTRACT_SERVICE');
export const FIND_ALL_CONTRACTS_SERVICE = Symbol('FIND_ALL_CONTRACTS_SERVICE');
export const FIND_CONTRACT_BY_ID_SERVICE = Symbol(
  'FIND_CONTRACT_BY_ID_SERVICE',
);
export const FIND_CONTRACT_BY_EMPRESA = Symbol('FIND_CONTRACT_BY_EMPRESA');
export const GET_CONTRACTS_BY_CITY_SERVICE = Symbol(
  'GET_CONTRACTS_BY_CITY_SERVICE',
);
export const INCREASE_USED_AMOUNT_IN_ITEMS_SERVICE = Symbol(
  'INCREASE_USED_AMOUNT_IN_ITEMS_SERVICE',
);
export const CREATE_PROPOSAL_SERVICE = Symbol('CREATE_PROPOSAL_SERVICE');
export const APPROVE_PROPOSAL_SERVICE = Symbol('APPROVE_PROPOSAL_SERVICE');
export const PROPOSAL_REPOSITORY = Symbol('PROPOSAL_REPOSITORY');
export const FIND_PROPOSAL_BY_FILTERS_SERVICE = Symbol(
  'FIND_PROPOSAL_BY_FILTERS_SERVICE',
);
export const CANCEL_PROPOSAL_SERVICE = Symbol('CANCEL_PROPOSAL_SERVICE');
