export const CONTRACT_REPOSITORY = Symbol('CONTRACT_REPOSITORY');
export const CREATE_CONTRACT_SERVICE = Symbol('CREATE_CONTRACT_SERVICE');
export const FIND_ALL_CONTRACTS_SERVICE = Symbol('FIND_ALL_CONTRACTS_SERVICE');
export const FIND_CONTRACT_BY_ID_SERVICE = Symbol(
  'FIND_CONTRACT_BY_ID_SERVICE',
);
export const FIND_CONTRACT_BY_EMPRESA = Symbol('FIND_CONTRACT_BY_EMPRESA');
export const GET_CONTRACTS_BY_CITY_SERVICE = Symbol(
  'GET_CONTRACTS_BY_CITY_SERVICE',
);
