export const CONTRACT_REPOSITORY = Symbol('CONTRACT_REPOSITORY');
export const CREATE_CONTRACT_SERVICE = Symbol('CREATE_CONTRACT_SERVICE');
export const FIND_ALL_CONTRACTS_SERVICE = Symbol('FIND_ALL_CONTRACTS_SERVICE');
