export const USER_REPOSITORY = Symbol('USER_REPOSITORY');
export const CREATE_USER_SERVICE = Symbol('CREATE_USER_SERVICE');
export const CHANGE_USER_CURRENT_CITY_SERVICE = Symbol('CHANGE_USER_CURRENT_CITY_SERVICE');
export const FIND_ALL_USERS_SERVICE = Symbol('FIND_ALL_USERS_SERVICE');
export const UPDATE_USER_SERVICE = Symbol('UPDATE_USER_SERVICE');