export const CREATE_CITY_SERVICE = Symbol('CREATE_CITY_SERVICE');
export const FIND_ALL_CITIES_SERVICE = Symbol('FIND_ALL_CITIES_SERVICE');
export const CREATE_CITY_COMPANY_SERVICE = Symbol(
  'CREATE_CITY_COMPANY_SERVICE',
);
export const CREATE_CITY_ORGAN_SERVICE = Symbol('CREATE_CITY_ORGAN_SERVICE');
export const FIND_ALL_CITY_COMPANIES_SERVICE = Symbol(
  'FIND_ALL_CITY_COMPANIES_SERVICE',
);
export const FIND_CITY_COMPANY_BY_ID_SERVICE = Symbol(
  'FIND_CITY_COMPANY_BY_ID_SERVICE',
);
export const UPDATE_CITY_COMPANY_SERVICE = Symbol(
  'UPDATE_CITY_COMPANY_SERVICE',
);
export const FIND_ALL_CITY_ORGANS_SERVICE = Symbol(
  'FIND_ALL_CITY_ORGANS_SERVICE',
);
export const FIND_CITY_ORGAN_BY_ID_SERVICE = Symbol(
  'FIND_CITY_ORGAN_BY_ID_SERVICE',
);
export const UPDATE_CITY_ORGAN_SERVICE = Symbol('UPDATE_CITY_ORGAN_SERVICE');
export const CITY_REPOSITORY = Symbol('CITY_REPOSITORY');
export const CITY_COMPANY_REPOSITORY = Symbol('CITY_COMPANY_REPOSITORY');
export const CITY_ORGAN_REPOSITORY = Symbol('CITY_ORGAN_REPOSITORY');
export const FIND_COMPANIES_BY_CITY_ID_SERVICE = Symbol(
  'FIND_COMPANIES_BY_CITY_ID_SERVICE',
);
export const FIND_ORGANS_BY_CITY_ID_SERVICE = Symbol(
  'FIND_ORGANS_BY_CITY_ID_SERVICE',
);
export const CNPJ_VALIDATION_SERVICE = Symbol('CNPJ_VALIDATION_SERVICE');
