export const CREATE_CITY_SERVICE = Symbol('CREATE_CITY_SERVICE');
export const FIND_ALL_CITIES_SERVICE = Symbol('FIND_ALL_CITIES_SERVICE');
export const CREATE_CITY_COMPANY_SERVICE = Symbol(
  'CREATE_CITY_COMPANY_SERVICE',
);
export const CREATE_CITY_ORGAN_SERVICE = Symbol('CREATE_CITY_ORGAN_SERVICE');
export const CITY_REPOSITORY = Symbol('CITY_REPOSITORY');
export const CITY_COMPANY_REPOSITORY = Symbol('CITY_COMPANY_REPOSITORY');
export const CITY_ORGAN_REPOSITORY = Symbol('CITY_ORGAN_REPOSITORY');
